### ISSUE TITLE
Do not work in Blender 4.5

### ISSUE THREAD

**Issue by maisamh80** [riouxr/Render-Manager#13]
First i want to say thanks a lot for your free addon
in Render-Manager 3.0.1 with blender 4.5.5 LTS i have received this error when i enable per pass denoising

Python: Traceback (most recent call last):
  File "C:\Users\lonard\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\user_default\render_manager\LayerManager.py", line 1235, in execute
    denoise_pass(node_tree, get_pass_name("diffuse_direct"), per_layer_node.outputs[get_pass_name("diffuse_direct")], normal_socket, albedo_socket, layer_color_node, x_pos + column_spacing + 300, y_pos - 150, noisy_passes)
  File "C:\Users\lonard\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\user_default\render_manager\LayerManager.py", line 1685, in denoise_pass
    target_slot = get_output_slot_by_name(dest_node, slot_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lonard\AppData\Roaming\Blender Foundation\Blender\4.5\extensions\user_default\render_manager\LayerManager.py", line 23, in get_output_slot_by_name
    for slot in node.file_output_items:
                ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'CompositorNodeOutputFile' object has no attribute 'file_output_items'

**Comment by riouxr** [comment]
Which version are you using? You may want to try the version before 3.0.0.
